#!/usr/bin/bash

if [ $# -eq 0 ]; then
    echo $'\nProvide at least one Python package name\n'
else
    for package in $@
    do
        pip install $package
        pip freeze | grep -i $package >> requirements.txt
    done
fi